backend:
  mode: trystero
trystero:
  firebase:
    apiKey: AIzaSyBrdTayHaSyCdcAE_85ZJ8-a5zTkfuimFo
    databaseURL: https://dps-udonarium-prod-default-rtdb.asia-southeast1.firebasedatabase.app
    projectId: dps-udonarium-prod
    appId: 1:575025205506:web:1bbc8ee443d1c4ebe0321b
